package commentary

import "github.com/esmshub/esms-go/engine/events"

// Commentary event types
const (
	// Goal-related events
	CommGoalEvent          = "GOAL"
	CommLateEqualiserEvent = "LATEEQUALISER"
	CommLateWinnerEvent    = "LATEWINNER"
	CommOwnGoalEvent       = "OWNGOAL"
	CommHatTrickEvent      = "HATTRICK"
	CommLandmarkEvent      = "LANDMARK"
	CommGoalCancelledEvent = "GOALCANCELLED"
	CommPenaltyGoalEvent   = "PEN_GOAL"

	// Foul-related events
	CommFoulEvent         = "FOUL"
	CommSeriousFoulEvent  = "SERIOUSFOUL"
	CommViolentFoulEvent  = "VIOLENTFOUL"
	CommProFoulEvent      = "PROFOUL"
	CommGKProFoulEvent    = "GK_PROFOUL"
	CommProFoulPenEvent   = "PROFOULPEN"
	CommGKProFoulPenEvent = "GK_PROFOULPEN"
	CommDiveEvent         = "DIVE"
	CommSpittingEvent     = "SPITTING"

	// Card-related events
	CommWarnedEvent              = "WARNED"
	CommYellowCardEvent          = "YELLOWCARD"
	CommBadYellowCardEvent       = "BADYELLOWCARD"
	CommDiveYellowCardEvent      = "DIVEYELLOWCARD"
	CommPersistantYellowEvent    = "PERSISTANTYELLOW"
	CommPersistant2ndYellowEvent = "PERSISTANT2NDYELLOW"
	CommSecondYellowCardEvent    = "SECONDYELLOWCARD"
	CommBadSecondYellowEvent     = "BADSECONDYELLOW"
	CommDiveSecondYellowEvent    = "DIVESECONDYELLOW"
	CommRedCardEvent             = "REDCARD"
	CommBadRedCardEvent          = "BADREDCARD"
	CommDiveRedCardEvent         = "DIVEREDCARD"

	// Penalty-related events
	CommPenaltyEvent              = "PENALTY"
	CommPenaltySaveEvent          = "PEN_SAVE"
	CommPenaltySaveCornerEvent    = "PEN_SAVE4CORNER"
	CommPenaltyOffTargetEvent     = "PEN_OFFTARGET"
	CommPenaltyShootoutEvent      = "PS_OUT_PEN"
	CommPenaltyShootoutStartEvent = "PENALTYSHOOTOUT"
	CommWonPenaltyShootoutEvent   = "WONPENALTYSHOOTOUT"

	// Match state events
	CommInjuryEvent                      = "INJURY"
	CommChangePositionEvent              = "CHANGEPOSITION"
	CommSubstitutionEvent                = "SUB"
	CommNoSubsLeftEvent                  = "NOSUBSLEFT"
	CommChangeTacticEvent                = "CHANGETACTIC"
	CommManOfMatchEvent                  = "MOM"
	CommInjuryTimeAEvent                 = "INJ_TIMEA"
	CommInjuryTimeBEvent                 = "INJ_TIMEB"
	CommSilverGoalEvent                  = "SILVER_GOAL"
	CommGoalScoredEvent                  = "GOAL"
	CommOwnGoalScoredEvent               = "OWNGOAL"
	CommAssistedChanceEvent              = "ASSISTEDCHANCE"
	CommAssistedChanceBeatsDefenderEvent = "GETS_PAST_ASS"
	CommChanceEvent                      = "CHANCE"
	CommChanceBeatsDefenderEvent         = "GETS_PAST"
	CommShotEvent                        = "SHOT"
	CommOneOnOneShotEvent                = "ONE_ON_ONE"
	CommShotOffTargetEvent               = "OFFTARGET"
	CommShotOffTargetDeflectionEvent     = "DEFLECTION4CORNER"
	CommOneOnOneShotOffTargetEvent       = "ONE_OFFTARGET"
	CommShotTackledEvent                 = "TACKLE"
	CommShotTackledCornerEvent           = "TACKLE4CORNER"
	CommShotSavedEvent                   = "SAVE"
	CommOneOnOneShotSavedEvent           = "ONE_SAVE"
	CommShotClearedEvent                 = "CLEARANCE"
	CommShotSavedCornerEvent             = "SAVE4CORNER"
	CommCornerEvent                      = "CORNER"
	CommCornerTakenEvent                 = "CORNER_TAKEN"
	CommCornerCaughtEvent                = "CORNER_CAUGHT"
	CommCornerClearedEvent               = "CORNER_CLEARED"
	CommCornerShotEvent                  = "CORNER_SHOT"

	// Match information events
	CommStartingFormationEvent = "STARTINGFORMATION"
	CommHalfTimeEvent          = "COMM_HALFTIME"
	CommFullTimeEvent          = "COMM_FULLTIME"
	CommExtraTimeEvent         = "COMM_EXTRATIME"
	CommAttemptsEvent          = "COMM_ATTEMPTS"
	CommInfoEvent              = "COMM_INFO"
	CommScoreEvent             = "COMM_SCORE"
	CommFoulsEvent             = "COMM_FOULS"
	CommTacklesEvent           = "COMM_TACKLES"
	CommPossessionEvent        = "COMM_POS"
	CommCornersEvent           = "COMM_CORNERS"
	CommDetailsEvent           = "COMM_DETAILS"
	CommStatsEvent             = "COMM_STATS"
	CommRedCardsEvent          = "COMM_RED"
	CommYellowCardsEvent       = "COMM_YELLOW"
	CommSentOffEvent           = "COMM_SENTOFF"
	CommBookedEvent            = "COMM_BOOKED"
	CommInjuredEvent           = "COMM_INJURED"
	CommSubsEvent              = "COMM_SUBS"
	CommPassesEvent            = "COMM_PASSES"
	CommAttendanceEvent        = "COMM_ATT"
	CommVenueEvent             = "COMM_VENUE"
	CommRefereeEvent           = "COMM_REF"
	CommGoalsEvent             = "COMM_GOALS"
	CommLineupsEvent           = "COMM_LINEUPS"
	CommPerformerEvent         = "COMM_PERFORMER"
	CommManOfMatchInfoEvent    = "COMM_MOM"
)

type CommentaryProvider interface {
	WriteCommentary(events.Event) error
}
